server:
  port: 8083

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  jpa:
    defer-datasource-initialization: true 
    hibernate:
      dd-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    config:
      import-check:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8099/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
